spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/loanservice?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: loanservice
    password: loanservice
  redis:
    host: redis
    port: 6379