version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: loanservice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'loanservice'
      MYSQL_USER: 'loanservice'
      MYSQL_PASSWORD: 'loanservice'
      MYSQL_DATABASE: 'loanservice'
    volumes:
      - "./mysql-init-script:/docker-entrypoint-initdb.d"
    networks:
      - loanservice-net
  redis:
    image: redis:latest
    container_name: loanservice-redis
    networks:
      - loanservice-net

networks:
  loanservice-net:
    external: true